### ISSUE TITLE
Mega Pokemon with Non-Mega Abilities

### ISSUE THREAD

**Issue by Arbbib** [Zarel/honko-damagecalc#309] opened 2019-05-01 19:53 UTC
Mega pokemon are loading up with their non-mega abilities. For example, if you pull up a mega pinsir set, it will have hyper cutter on it

**Comment by AustinXII** [comment] 2019-05-01 19:58
@asgdf didn’t you fix this?

**Comment by asgdf** [comment] 2019-05-04 01:48
I fixed it for switching between formes, but here the issue is probably that Smogon has the set with the mega as the pokemon but the base's ability, and we're taking that at face value. Not sure how I'd fix that, we can't just always override with the default ability because we allow selecting different ones.

**Comment by AustinXII** [comment] 2019-05-04 03:50
Oh it’s __that__ issue, I requested them add a further evolution to support mega Pokémon because that seems to make more sense but I haven’t gotten a reply. Thanks @asgdf

**Comment by Zarel** [comment] 2019-05-06 08:24
You _can_ just fix it in your own code...

**Comment by AustinXII** [comment] 2019-05-06 15:06
@Zarel yes but then there is an issue of honko’s script overriding the changes every time, or adding back the sets with the base forme abilities..

**Comment by AustinXII** [comment] 2019-05-07 00:33
@Honko opinions?

**Comment by Zarel** [comment] 2019-05-07 01:46
I meant in your code, not in your data. :[

**Comment by AustinXII** [comment] 2019-05-07 02:01
@Zarel it would be incredibly ugly code :[, I'd rather change the setdex files to just have the mega's at the bottom and possibly not have honko's script gather mega pokemon data

**Comment by Zarel** [comment] 2019-05-07 02:03
Sure, it's an obvious workaround and may be "ugly" in that sense, but you can just mark it with a comment. It should only be a one-liner anyway.

**Comment by AustinXII** [comment] 2019-05-07 02:07
@Zarel yeah true. I still hate how pokemon imported from smogon by users would still have their base forme abilities because of how smogon dex works. If they changed that we would have both issues fixed :/

**Comment by Honko** [comment] 2019-05-07 02:24
@AustinXII I thought I fixed the setdex side of this in https://github.com/Zarel/honko-damagecalc/pull/306. Can you clarify what's not working?

**Comment by AustinXII** [comment] 2019-05-07 03:03
@Honko you can't import a mega pokemon without getting is default ability, I can't load your changes rn because im on mobile, but did you change the mega pokemon sets to have their non-base form ability? If so that's one of the issues fixed :) the second will be fixed in #314

**Comment by scheibo** [comment] 2019-09-03 02:22
I think this is fixed?

**Closed by scheibo** 2019-09-03 02:22 UTC
