### ISSUE TITLE
Sea Incense isn't correctly calculating damage

### ISSUE THREAD

**Issue by nineliiife** [Zarel/honko-damagecalc#326] opened 2019-07-22 18:24 UTC
![image](https://user-images.githubusercontent.com/28803606/61655112-cb37ca80-acb5-11e9-9643-86b6d39febeb.png)

As above, both Splash plate and Sea Incense should apply a 20% boost, but are producing different outputs. It looks like Sea Incense is being applied twice, resulting in a 1.44x modifier instead

**Comment by AustinXII** [comment] 2019-07-22 22:02
@scheibo is this another bug caused by you?

**Comment by scheibo** [comment] 2019-07-22 22:12
I don't know. It seems less likely, but I'll look at it while I'm fixing the others :)

**Comment by scheibo** [comment] 2019-07-22 22:12
Oh wait, it could be the same issue I just fixed with mutation TBH

**Comment by scheibo** [comment] 2019-07-22 22:19
No, just synced to 0d781bb4d72a1d166eb1c255877b73757069774f and its present then

**Closed** 2019-07-23 04:46 UTC
